# Generated by Django 3.1.14 on 2025-05-26 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffGallery',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='webkafedra_staffgallery', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ImageLinkPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='webkafedra_imagelinkpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(help_text='Введите текст ссылки', verbose_name='Текст ссылки')),
                ('url', models.URLField(help_text='Введите URL, на который будет вести ссылка', max_length=255, verbose_name='URL ссылки')),
                ('image', filer.fields.image.FilerImageField(help_text='Загрузите изображение', on_delete=django.db.models.deletion.CASCADE, related_name='image_link_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
